Added checks for gdate and gstat for MacOS

diff --git a/podget b/podget
--- a/podget
+++ b/podget
@@ -1356,6 +1356,20 @@ case "$uname" in
         else
             hash -p "$(hash -t gexpr)" expr
         fi
+        if ! hash gdate >/dev/null 2>&1; then
+            echo "GNU Date Required."
+            echo "Try 'brew install gdate'  (see htts://brew.sh for details)"
+            DARWIN_EXIT=1
+        else
+            hash -p "$(hash -t gdate)" date
+        fi
+        if ! hash gstat >/dev/null 2>&1; then
+            echo "GNU Stat Required."
+            echo "Try 'brew install gstat'  (see htts://brew.sh for details)"
+            DARWIN_EXIT=1
+        else
+            hash -p "$(hash -t gstat)" stat
+        fi
         if (( DARWIN_EXIT > 0 )); then
             CLEANUP_AND_EXIT 1
         fi
