Added EXPR support for Mac Compatibility

diff --git a/podget b/podget
--- a/podget
+++ b/podget
@@ -635,18 +635,31 @@ TEXT_ASX_END
 #                                                                                                                                }}}
 # ----------------------------------------------------------------------------------------------------------------------------------
 # Portability code                                                                                                               {{{
-# This allows Gnu/Linux podget to also run on BSD/Mac OSX
+# This allows Gnu/Linux podget to also run on Mac OSX
 
 if [ "$(uname)" = "Darwin" ]; then
-  if ! hash gsed >/dev/null 2>&1; then
-    echo "GNU Sed Required."
-    echo "Try 'brew install gnu-sed'  (see htts://brew.sh for details)"
-    exit 1
-  else
-    SED="gsed"
-  fi
+    DARWIN_EXIT=0
+
+    if ! hash gsed >/dev/null 2>&1; then
+        echo "GNU Sed Required."
+        echo "Try 'brew install gnu-sed'  (see htts://brew.sh for details)"
+        DARWIN_EXIT=1
+    else
+        SED="gsed"
+    fi
+    if ! hash gexpr >/dev/null 2>&1; then
+        echo "GNU Expr Required."
+        echo "Try 'brew install coreutils'  (see htts://brew.sh for details)"
+        DARWIN_EXIT=1
+    else
+        EXPR="gexpr"
+    fi
+    if (( DARWIN_EXIT > 0 )); then
+        CLEANUP_AND_EXIT 1
+    fi
 else
-  SED="sed"
+    SED="sed"
+    EXPR="expr"
 fi
 
 #                                                                                                                                }}}
@@ -1011,7 +1024,7 @@ filenameFixFormat() {
 
     # Filename format fix for podcasts hosted on http://lbc.audioagain.com.
     if [[ -n ${FILENAME_FORMATFIX2+set} ]] && (( FILENAME_FORMATFIX2 > 0 )); then
-        if (( $(expr "${MODIFIED_FILENAME}" : "[0-9a-zA-Z]\+[&]amp;source=podcast.php[&]amp;channel_id=[0-9]\+\$") > 0 )); then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : "[0-9a-zA-Z]\+[&]amp;source=podcast.php[&]amp;channel_id=[0-9]\+\$") > 0 )); then
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | ${SED} 's/.*stream.mp3[?]guid=\([0-9]\+\)-\([0-9]\+\)\/\([0-9]\+\)\/.*/\1-\2-\3.mp3/')
             if (( DEBUG == 1 )) ; then
                 echo "${DEBUG_LEADER} FILENAME FORMAT(2) FIXED: ${MODIFIED_FILENAME}"
@@ -1024,7 +1037,7 @@ filenameFixFormat() {
     # Filename format fix for podcasts hosted on http://www.catradio.cat
     if [[ -n ${FILENAME_FORMATFIX3+set} ]] && (( FILENAME_FORMATFIX3 > 0 )); then
         echo "INSIDE FILENAME_FORMATFIX3"
-        if (( $(expr "${MODIFIED_FILENAME}" : "[0-9]\+\.mp3\?[&]programa=[0-9a-Z+=%&;]*\$") > 0 )); then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : "[0-9]\+\.mp3\?[&]programa=[0-9a-Z+=%&;]*\$") > 0 )); then
             echo "FOUND FILENAME_FORMATFIX3"
             echo "CAT RADIO FILENAME ${MODIFIED_FILENAME}"
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | ${SED} 's/\(.*\)\.mp3\(.*\)/\1\.mp3/g')
@@ -1038,7 +1051,7 @@ filenameFixFormat() {
 
     # Remove "?referrer=rss" from filename as included with some feeds like Vimcasts.org
     if [[ -n ${FILENAME_FORMATFIX5+set} ]] &&  (( FILENAME_FORMATFIX5 > 0 )); then
-        if (( $(expr "${MODIFIED_FILENAME}" : "[-0-9a-zA-Z_]\+\.[gmopv34]\+[?]referrer=rss") > 0 )); then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : "[-0-9a-zA-Z_]\+\.[gmopv34]\+[?]referrer=rss") > 0 )); then
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | ${SED} -r 's/([-A-Za-z0-9_]+.[ogmpv34]+)[?]referrer=rss/\1/g')
             if (( DEBUG == 1 )) ; then
                 echo "${DEBUG_LEADER} FILENAME FORMAT(5) FIXED: ${MODIFIED_FILENAME}"
@@ -1048,7 +1061,7 @@ filenameFixFormat() {
 
     # ZDF podcast filename fix
     if [[ -n ${FILENAME_FORMATFIX6+set} ]] && (( FILENAME_FORMATFIX6 > 0 )); then
-        if (( $(expr "${MODIFIED_FILENAME}" : "[-_0-9a-zA-Z]\+\.[gmopv34]\+[?][-_+0-9]\+") > 0 )); then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : "[-_0-9a-zA-Z]\+\.[gmopv34]\+[?][-_+0-9]\+") > 0 )); then
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | sed -ru 's/([-_A-Za-z0-9]+.[ogmpv3-4]+)[?][-+0-9]*/\1/g')
             if (( DEBUG == 1 )) ; then
                 echo "${DEBUG_LEADER} FILENAME FORMAT(6) FIXED: ${MODIFIED_FILENAME}"
@@ -1065,7 +1078,7 @@ filenameFixFormat() {
     # with extended regex and buffers limited
     # wget -O - http://radiofrance-podcast.net/podcast09/rss_12036.xml | grep enclosure | sed -ru 's/.*(media_url=.*[.][gmopv34]+)"\ .*/\1/' | sed -ru 's/.*%2F([-0-9A-Za-z_.]+[.][gmopv34]+)/\1/'
     if [[ -n ${FILENAME_FORMATFIX7+set} ]] && (( FILENAME_FORMATFIX7 > 0 )); then
-        if (( $(expr "${MODIFIED_FILENAME}" : "[+_%&=?.0-9a-zA-Z]*media_url=http") > 0 )); then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : "[+_%&=?.0-9a-zA-Z]*media_url=http") > 0 )); then
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | ${SED} -ru 's/.*(media_url=http.*[.][gmopv34]+)"\ .*/\1/' | ${SED} -ru 's/.*%2F([-0-9A-Za-z_.]+[.][gmopv34]+)/\1/')
             if (( DEBUG == 1 )) ; then
                 echo "${DEBUG_LEADER} FILENAME FORMAT(7) FIXED: ${MODIFIED_FILENAME}"
@@ -1082,7 +1095,7 @@ filenameFixFormat() {
     # to separate these feeds to their own configuration and serverlist files.  They can then be loaded by using the -c and
     # --serverlist flags on the command line.
     if [[ -n ${FILENAME_FORMATFIX8+set} ]] && (( FILENAME_FORMATFIX8 > 0 )); then
-        if (( $(expr "${MODIFIED_FILENAME}" : "stream[.]mp3[?]client_id=[0-9a-zA-Z]\+") > 0 )); then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : "stream[.]mp3[?]client_id=[0-9a-zA-Z]\+") > 0 )); then
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | ${SED} -ru 's/(stream[.]mp3)[?]client_id=[0-9A-Za-z]+/\1/')
             if (( DEBUG == 1 )) ; then
                 echo "${DEBUG_LEADER} FILENAME FORMAT(8) FIXED: ${MODIFIED_FILENAME}"
@@ -1094,7 +1107,7 @@ filenameFixFormat() {
     # Enclosure URLs have "?keyed=true&amp;source=rss" appended to them.  This fix removes that string.
     # It should work for Audioboo podcasts and others with similar formating.
     if [[ -n ${FILENAME_FORMATFIX9+set} ]] && (( FILENAME_FORMATFIX9 > 0 )); then
-        if (( $(expr "${MODIFIED_FILENAME}" : "[-_0-9A-z]\+[.][gmopv34]\+[?][%&;=0-9a-zA-Z]\+") > 0 )) ; then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : "[-_0-9A-z]\+[.][gmopv34]\+[?][%&;=0-9a-zA-Z]\+") > 0 )) ; then
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | ${SED} -ru 's/([-_A-Za-z0-9]+[.][ogmpv3-4]+)[?][%&;=A-Za-z0-9]+/\1/g')
             if (( DEBUG == 1 )) ; then
                 echo "${DEBUG_LEADER} FILENAME FORMAT(9) FIXED: ${MODIFIED_FILENAME}"
@@ -1106,7 +1119,7 @@ filenameFixFormat() {
     # Filenames are generally long strings of numbers and letters, with the actual episode name being defined after the '?'
     # This extracts the episode name and uses it for the filename.
     if [[ -n ${FILENAME_FORMATFIX10+set} ]] && (( FILENAME_FORMATFIX10 > 0 )); then
-        if (( $(expr "${MODIFIED_FILENAME}" : "[-0-9A-Za-z_]\+[.][MmPp3]\+[?][-0-9A-Za-z%=]\+%26episodeName%3D[-0-9A-Za-z%.*]\+%26episodeKind%3D") > 0 )); then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : "[-0-9A-Za-z_]\+[.][MmPp3]\+[?][-0-9A-Za-z%=]\+%26episodeName%3D[-0-9A-Za-z%.*]\+%26episodeKind%3D") > 0 )); then
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | ${SED} -ru 's/.*%26episodeName%3D([-._%A-Za-z0-9*]+)%26episodeKind[-%&;=A-Za-z0-9]+/\1.mp3/g' | ${SED} -ru 's/%2B/_/g;s/%25[0-9ACF]{2}//g;s/[*]//g')
             if (( DEBUG == 1 )) ; then
                 echo "${DEBUG_LEADER} FILENAME FORMAT(10) FIXED: ${MODIFIED_FILENAME}"
@@ -1116,7 +1129,7 @@ filenameFixFormat() {
 
     # Fix improperly formated filenames (fixes filename.mp3?123456 to filename123456.mp3)
     if [[ -n ${FILENAME_FORMATFIX+set} ]] && (( FILENAME_FORMATFIX > 0 )); then
-        if (( $(expr "${MODIFIED_FILENAME}" : ".*\.mp3..*$") > 0 )); then
+        if (( $(${EXPR} "${MODIFIED_FILENAME}" : ".*\.mp3..*$") > 0 )); then
             MODIFIED_FILENAME=$(echo "${MODIFIED_FILENAME}" | ${SED} 's/\.mp3\(.*\)/\1.mp3/')
             if (( DEBUG == 1 )) ; then
                 echo "${DEBUG_LEADER} FILENAME FORMAT FIXED: ${MODIFIED_FILENAME}"
@@ -1653,7 +1666,7 @@ while read -r -d $'\0' FILE ; do
         TEST_SESSION=1
         # shellcheck disable=SC2094
         while read -r LINE ; do
-            TEST_Index=$(expr "${LINE}" : "^[Cc]onfig\sfile:")
+            TEST_Index=$(${EXPR} "${LINE}" : "^[Cc]onfig\sfile:")
             if [[ "A${TEST_Index}" != "A" ]]; then
                 TEST_File=$(echo "${LINE}" | ${SED} -n -e 's/^[^:]\+:\s\(.*\)$/\1/p')
                 if [[ ${TEST_File} == "${CONFIG_CORE}" ]] ; then
@@ -1852,7 +1865,7 @@ if (( CLEANUP_ONLY == 0 )) && [[ -z ${IMPORT_OPML+set} && -z ${EXPORT_OPML+set} 
             unset ATOM_FILTER_LANG
 
             # Enable user configured no category.
-            if (( $(expr "${FEED_CATEGORY}" : "No_Category") > 0 )); then
+            if (( $(${EXPR} "${FEED_CATEGORY}" : "No_Category") > 0 )); then
                 # Set to single period which is a bashism for current directory.
                 FEED_CATEGORY="."
             fi
@@ -1860,62 +1873,62 @@ if (( CLEANUP_ONLY == 0 )) && [[ -z ${IMPORT_OPML+set} && -z ${EXPORT_OPML+set} 
             FEED_CATEGORY=$(echo "${FEED_CATEGORY}" | ${SED} -e "s#%YY%#$(date +%Y)#" -e "s#%MM%#$(date +%m)#" -e "s#%DD%#$(date +%d)#" )
 
             # Extract PASSWORD from FEED_NAME if found.
-            if (( $(expr "${FEED_NAME}" : ".*PASS:[^ $]\+.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*PASS:[^ $]\+.*") > 0 )); then
                 URL_PASSWORD=$(echo "${FEED_NAME}" | ${SED} -e 's/.*\(PASS:[^ $]\+\).*/\1/' -e 's/PASS:\(.*\)/\1/')
                 FEED_NAME=${FEED_NAME/PASS:+([^[:space:]])}
             fi
 
             # Extract USERNAME from FEED_NAME if found.
-            if (( $(expr "${FEED_NAME}" : ".*USER:[^ $]\+.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*USER:[^ $]\+.*") > 0 )); then
                 URL_USERNAME=$(echo "${FEED_NAME}" | ${SED} -e 's/.*\(USER:[^ $]\+\).*/\1/' -e 's/USER:\(.*\)/\1/')
                 FEED_NAME=${FEED_NAME/USER:+([^[:space:]])}
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*OPT_CONTENT_DISPOSITION.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_CONTENT_DISPOSITION.*") > 0 )); then
                 WGET_OPTION_DISPOSITION=1
                 FEED_NAME=${FEED_NAME/OPT_CONTENT_DISPOSITION}
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*OPT_DISPOSITION_FAIL.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_DISPOSITION_FAIL.*") > 0 )); then
                 WGET_OPTION_DISPOSITION_FAIL=1
                 FEED_NAME=${FEED_NAME/OPT_DISPOSITION_FAIL}
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*OPT_FEED_ORDER_ASCENDING.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_FEED_ORDER_ASCENDING.*") > 0 )); then
                 FEED_SORT_ORDER="ASCENDING"
                 FEED_NAME=${FEED_NAME/OPT_FEED_ORDER_ASCENDING}
             fi
 
             # The following two tags are handled in a later loop and so only need to be removed here.
-            if (( $(expr "${FEED_NAME}" : ".*OPT_FEED_PLAYLIST_NEWFIRST.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_FEED_PLAYLIST_NEWFIRST.*") > 0 )); then
                 FEED_NAME=${FEED_NAME/OPT_FEED_PLAYLIST_NEWFIRST}
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*OPT_FEED_PLAYLIST_OLDFIRST.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_FEED_PLAYLIST_OLDFIRST.*") > 0 )); then
                 FEED_NAME=${FEED_NAME/OPT_FEED_PLAYLIST_OLDFIRST}
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*OPT_FILENAME_LOCATION.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_FILENAME_LOCATION.*") > 0 )); then
                 WGET_OPTION_FILENAME_LOCATION=1
                 FEED_NAME=${FEED_NAME/OPT_FILENAME_LOCATION}
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*OPT_FILENAME_RENAME_MDATE.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_FILENAME_RENAME_MDATE.*") > 0 )); then
                 POST_WGET_RENAME_MDATE=1
                 FEED_NAME=${FEED_NAME/OPT_FILENAME_RENAME_MDATE}
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*ATOM_FILTER_SIMPLE.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*ATOM_FILTER_SIMPLE.*") > 0 )); then
                 ATOM_FILTER_SIMPLE=1
                 FEED_NAME=${FEED_NAME/ATOM_FILTER_SIMPLE}
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*ATOM_FILTER_TYPE=.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*ATOM_FILTER_TYPE=.*") > 0 )); then
                 ATOM_FILTER_TYPE=$(echo "${FEED_NAME}" | ${SED} -n -e 's/.*ATOM_FILTER_TYPE="\([^"]\+\)".*/\1/p')
                 FEED_NAME=$(echo "${FEED_NAME}" | ${SED} -n -e 's/\(^.*\)ATOM_FILTER_TYPE="[^"]\+"\(.*\)/\1\2/p')
             fi
 
-            if (( $(expr "${FEED_NAME}" : ".*ATOM_FILTER_LANG=.*") > 0 )); then
+            if (( $(${EXPR} "${FEED_NAME}" : ".*ATOM_FILTER_LANG=.*") > 0 )); then
                 ATOM_FILTER_LANG=$(echo "${FEED_NAME}" | ${SED} -n -e 's/.*ATOM_FILTER_LANG="\([^"]\+\)".*/\1/p')
                 FEED_NAME=$(echo "${FEED_NAME}" | ${SED} -n -e 's/\(^.*\)ATOM_FILTER_LANG="[^"]\+"\(.*\)/\1\2/p')
             fi
@@ -2712,17 +2725,17 @@ if [[ -z ${IMPORT_OPML+set} && -z ${EXPORT_OPML+set} && -z ${IMPORT_PCAST+set} ]
                     continue
                 fi
                 # Enable user configured no category.
-                if (( $(expr "${FEED_CATEGORY}" : "No_Category") > 0 )); then
+                if (( $(${EXPR} "${FEED_CATEGORY}" : "No_Category") > 0 )); then
                     # Set to single period which is a bashism for current directory.
                     FEED_CATEGORY="."
                 fi
 
-                if (( $(expr "${FEED_NAME}" : ".*OPT_FEED_PLAYLIST_NEWFIRST.*") > 0 )); then
+                if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_FEED_PLAYLIST_NEWFIRST.*") > 0 )); then
                     FEED_FULL_PLAYLIST=1
                     FEED_NAME=${FEED_NAME/OPT_FEED_PLAYLIST_NEWFIRST}
                 fi
 
-                if (( $(expr "${FEED_NAME}" : ".*OPT_FEED_PLAYLIST_OLDFIRST.*") > 0 )); then
+                if (( $(${EXPR} "${FEED_NAME}" : ".*OPT_FEED_PLAYLIST_OLDFIRST.*") > 0 )); then
                     FEED_FULL_PLAYLIST=2
                     FEED_NAME=${FEED_NAME/OPT_FEED_PLAYLIST_OLDFIRST}
                 fi
@@ -2743,11 +2756,11 @@ if [[ -z ${IMPORT_OPML+set} && -z ${EXPORT_OPML+set} && -z ${IMPORT_PCAST+set} ]
                     FEED_NAME=${FEED_NAME/OPT_FILENAME_RENAME_MDATE}
                     FEED_NAME=${FEED_NAME/ATOM_FILTER_SIMPLE}
 
-                    if (( $(expr "${FEED_NAME}" : ".*ATOM_FILTER_TYPE=.*") > 0 )); then
+                    if (( $(${EXPR} "${FEED_NAME}" : ".*ATOM_FILTER_TYPE=.*") > 0 )); then
                         FEED_NAME=$(echo "${FEED_NAME}" | ${SED} -n -e 's/\(^.*\)ATOM_FILTER_TYPE="[^"]\+"\(.*\)/\1\2/p')
                     fi
 
-                    if (( $(expr "${FEED_NAME}" : ".*ATOM_FILTER_LANG=.*") > 0 )); then
+                    if (( $(${EXPR} "${FEED_NAME}" : ".*ATOM_FILTER_LANG=.*") > 0 )); then
                         FEED_NAME=$(echo "${FEED_NAME}" | ${SED} -n -e 's/\(^.*\)ATOM_FILTER_LANG="[^"]\+"\(.*\)/\1\2/p')
                     fi
 
@@ -2926,12 +2939,12 @@ if [[ -n ${EXPORT_OPML+set} ]]; then
         FEED_NAME=${FEED_NAME/USER:+([^[:space:]])}
 
         # Remove any residual trailing spaces from ${FEED_NAME}
-        while (( $(expr "${FEED_NAME}" : ".*[ ]\+$") > 0 )); do
+        while (( $(${EXPR} "${FEED_NAME}" : ".*[ ]\+$") > 0 )); do
             FEED_NAME=${FEED_NAME%[ ]*}
         done
 
         # Remove any residual leading spaces from ${FEED_NAME}
-        while (( $(expr "${FEED_NAME}" : "[ ]\+.*$") > 0 )); do
+        while (( $(${EXPR} "${FEED_NAME}" : "[ ]\+.*$") > 0 )); do
             FEED_NAME=${FEED_NAME#[ ]*}
         done
 
